### ISSUE TITLE
@keyframes?

### ISSUE THREAD

**Issue by 0xHarrison** [mirisuzanne/compass-animation#8]
I kept getting this error:
Invalid CSS after "@keyframes": expected selector or at-rule, was "(in-fade) {")
any ideas?

@keyframes(in-fade) {
    0%{
        @include opacity(0);
    }
    100%{
        @include opacity(1);
    }
}

am I doing something wrong here?

version:
Sass 3.2.0.alpha.275 (Bleeding Edge)
Compass 0.12.2 (Alnilam)

**Comment by mirisuzanne** [comment]
That should be `@include keyframes(...) {...}`, but I guess maybe you figured that out.

**Comment by 0xHarrison** [comment]
yea I did, thanks.
https://github.com/ericam/compass-animation#for-example should be changed to `@include` tho.

**Comment by mirisuzanne** [comment]
Fixed. Thanks!
