### ISSUE TITLE
Failing to Load: Syntax error: Undefined variable

### ISSUE THREAD

**Issue by VinSpee** [mirisuzanne/compass-animation#9]
Getting this error when simply trying to load the library.

```
Syntax error: Undefined variable: "$experimental-support-for-mozilla".
        on line 39 of /Users/vspeelman/.rvm/gems/ruby-1.9.3-p194/gems/animation-0.1.alpha.3/stylesheets/animation/animate/fading/_fading-exits.scss, in `keyframes'
        from line 2 of /Users/vspeelman/.rvm/gems/ruby-1.9.3-p194/gems/animation-0.1.alpha.3/stylesheets/animation/animate/fading/_fading-exits.scss
        from line 2 of /Users/vspeelman/.rvm/gems/ruby-1.9.3-p194/gems/animation-0.1.alpha.3/stylesheets/animation/animate/_fading.scss
        from line 23 of /Users/vspeelman/.rvm/gems/ruby-1.9.3-p194/gems/animation-0.1.alpha.3/stylesheets/animation/_animate.scss
        from line 4 of /Users/vspeelman/projects/podproxy/src/ui/sass/style.sass
```

**Comment by cri5ti** [comment]
I've had the same error, and after lots of debugging I realised I forgot to import compass.

So just add `@import "compass";` to the top of your .scss

**Comment by VinSpee** [comment]
Seems as though I had to @import "compass"; in the top of the specific file that i'm importing animation in. strange behavior.

**Comment by mirisuzanne** [comment]
Shouldn't have to be the same file, as long as it is imported before compass-animation. Really, compass-animation should take care of that import for you. Even more so, compass should release 0.13 so we can finally have animation in the core and not as a plugin.

**Comment by mezis** [comment]
Just an opinion really, but importing all of compass is unnecessary and can easily slow you down. On [one project](http://github.com/mezis/appfab) I ended up saving 60% of my asset build time by importing only the compass components I needed in each of my Sass partials, which translated into 60s saved off each 90s deploy. In development, each rebuild/reload after changing some styling is accordingly faster, too. 

For `compass-animation` to work you only really need (apparently) to

```
@import compass/support
@import compass/css3/shared
```

which is much faster to compile!
